import { createContext, useContext, useState, ReactNode, useCallback } from 'react';

export type Lang = 'de' | 'en';

const translations = {
  // Dashboard / Header
  'myTour': { de: 'Meine Tour', en: 'My Tour' },
  'startDay': { de: 'Tagesstart durchführen', en: 'Start the day' },
  'all': { de: 'Alle', en: 'All' },
  'open': { de: 'Offen', en: 'Open' },
  'done': { de: 'Erledigt', en: 'Completed' },
  'swipeHint': { de: '← Überspringen · Swipe · Erledigen →', en: '← Skip · Swipe · Complete →' },
  'visits': { de: 'Besuche', en: 'Visits' },

  // Greeting
  'greet.superWork': { de: 'Super Arbeit!', en: 'Great work!' },
  'greet.superWorkSub': { de: 'Fast geschafft – Du hast heute richtig abgeliefert!', en: 'Almost done – you really delivered today!' },
  'greet.endSpurt': { de: 'Endspurt!', en: 'Final stretch!' },
  'greet.endSpurtSub': { de: 'Der Tag neigt sich – gleich hast du Feierabend!', en: 'Day is ending – almost time to clock out!' },
  'greet.afternoon': { de: 'Nachmittag, weiter geht\'s!', en: 'Afternoon, keep going!' },
  'greet.afternoonSub': { de: 'Du machst das großartig. Noch ein paar Stopps!', en: 'You\'re doing great. A few more stops!' },
  'greet.goingWell': { de: 'Läuft bei dir!', en: 'Going well!' },
  'greet.goingWellSub': { de: 'Guter Rhythmus – weiter so, Champion!', en: 'Good rhythm – keep it up, Champion!' },
  'greet.morning': { de: 'Guten Morgen!', en: 'Good morning!' },
  'greet.morningSub': { de: 'Ein neuer Tag wartet – viel Erfolg auf der Tour!', en: 'A new day awaits – good luck on your tour!' },
  'greet.evening': { de: 'Guten Abend!', en: 'Good evening!' },
  'greet.eveningSub': { de: 'Feierabend! Ruh dich aus, morgen geht\'s weiter.', en: 'Off work! Rest up, tomorrow continues.' },
  'rainAt': { de: 'Regen ab 14:00', en: 'Rain from 2 PM' },

  // Bottom nav
  'nav.tour': { de: 'Tour', en: 'Tour' },
  'nav.route': { de: 'Route', en: 'Route' },
  'nav.workTime': { de: 'Arbeitszeit', en: 'Work Time' },
  'nav.storage': { de: 'Lager', en: 'Storage' },
  'nav.driverID': { de: 'Ausweis', en: 'ID Card' },

  // Work Time Banner
  'workBanner.title': { de: 'Arbeit noch nicht gestartet', en: 'Work not started yet' },
  'workBanner.subtitle': { de: 'Bitte starte deine Arbeitszeit bevor du losfährst', en: 'Please start your work time before departing' },
  'workBanner.button': { de: 'Jetzt starten', en: 'Start now' },

  // Driver ID page
  'driverID.title': { de: 'Fahrerausweis', en: 'Driver ID' },
  'driverID.officialDoc': { de: 'Offizielles Dokument', en: 'Official Document' },
  'driverID.forInspection': { de: 'Zur Vorlage bei Verkehrskontrolle', en: 'For traffic inspection' },
  'driverID.company': { de: 'Unternehmen', en: 'Company' },
  'driverID.taxId': { de: 'USt-IdNr.', en: 'Tax ID' },
  'driverID.registration': { de: 'Handelsregister', en: 'Registration' },
  'driverID.driver': { de: 'Fahrer', en: 'Driver' },
  'driverID.licenseClass': { de: 'Führerschein', en: 'License' },
  'driverID.vehicle': { de: 'Fahrzeug', en: 'Vehicle' },
  'driverID.plate': { de: 'Kennzeichen', en: 'License Plate' },
  'driverID.routePlan': { de: 'Tourenplan', en: 'Route Plan' },
  'driverID.stops': { de: 'Stopps', en: 'Stops' },
  'driverID.footer': { de: 'Dieses Dokument dient zur Vorlage bei behördlichen Kontrollen. © German Waste Management GmbH', en: 'This document is for presentation during official inspections. © German Waste Management GmbH' },
  'driverID.signature': { de: 'Unterschrift des Fahrers', en: 'Driver Signature' },
  'driverID.officialId': { de: 'Offizielle ID', en: 'Official ID' },
  'driverID.hireDate': { de: 'Anstellungsdatum', en: 'Hire Date' },
  'driverID.tourOverview': { de: 'Tourenübersicht', en: 'Tour Overview' },
  'driverID.tourOverviewSub': { de: 'Für Polizeikontrolle', en: 'For police inspection' },

  // Tour Overview page
  'tour.overviewTitle': { de: 'Tourenübersicht', en: 'Tour Overview' },
  'tour.company': { de: 'Unternehmen', en: 'Company' },
  'tour.driver': { de: 'Fahrer', en: 'Driver' },
  'tour.plate': { de: 'Kennzeichen', en: 'Plate' },
  'tour.purpose': { de: 'Zweck', en: 'Purpose' },
  'tour.totalStops': { de: 'Stopps', en: 'Stops' },
  'tour.duration': { de: 'Zeitraum', en: 'Duration' },
  'tour.estimated': { de: 'geschätzt', en: 'estimated' },
  'tour.customerList': { de: 'Kundenliste', en: 'Customer List' },
  'tour.done': { de: 'Erledigt', en: 'Done' },
  'tour.inProgress': { de: 'Aktiv', en: 'Active' },
  'tour.planned': { de: 'Geplant', en: 'Planned' },
  'tour.kilometer': { de: 'Kilometerstand', en: 'Odometer' },
  'tour.startKm': { de: 'Start KM', en: 'Start KM' },
  'tour.currentKm': { de: 'Aktuell KM', en: 'Current KM' },
  'tour.endKm': { de: 'Ende KM', en: 'End KM' },
  'tour.digitalProof': { de: 'Digitaler Nachweis', en: 'Digital Proof' },
  'tour.routeId': { de: 'Routen-ID', en: 'Route ID' },
  'tour.active': { de: 'Aktiv', en: 'Active' },

  // Menu
  'menu': { de: 'Menü', en: 'Menu' },
  'menu.work': { de: 'Arbeit', en: 'Work' },
  'menu.communication': { de: 'Kommunikation', en: 'Communication' },
  'menu.admin': { de: 'Verwaltung', en: 'Administration' },
  'menu.workTime': { de: 'Arbeitszeit', en: 'Work Time' },
  'menu.workTimeSub': { de: 'Start/Ende & Pausen', en: 'Start/End & Breaks' },
  'menu.morningFlow': { de: 'Tagesstart', en: 'Start the Day' },
  'menu.morningFlowSub': { de: 'Checkliste & Tagesübersicht', en: 'Checklist & daily overview' },
  'menu.tourPlan': { de: 'Tourenplan', en: 'Tour Plan' },
  'menu.tourPlanSub': { de: 'Tagesplan (Polizei)', en: 'Day plan (Police)' },
  'menu.newCustomer': { de: 'Neukunde', en: 'New Customer' },
  'menu.newCustomerSub': { de: 'Neuen Kunden registrieren & Vertrag abschließen', en: 'Register new customer & sign contract' },
  'menu.reportProblem': { de: 'Problem melden', en: 'Report Problem' },
  'menu.reportProblemSub': { de: 'Panne, Stau oder andere Störung melden', en: 'Report breakdown, traffic jam or other issue' },
  'menu.messages': { de: 'Nachrichten', en: 'Messages' },
  'menu.messagesSub': { de: 'Chat mit Disposition', en: 'Chat with Dispatch' },
  'menu.whatsapp': { de: 'WhatsApp', en: 'WhatsApp' },
  'menu.whatsappSub': { de: 'Zentrale kontaktieren', en: 'Contact HQ' },
  'menu.leave': { de: 'Urlaub & Krankmeldung', en: 'Leave & Sick Report' },
  'menu.leaveSub': { de: 'Anträge stellen & Status', en: 'Submit requests & Status' },
  'menu.fuel': { de: 'Tankbelege', en: 'Fuel Receipts' },
  'menu.fuelSub': { de: 'Diesel & AdBlue', en: 'Diesel & AdBlue' },
  'menu.performance': { de: 'Leistung', en: 'Performance' },
  'menu.performanceSub': { de: 'Meine Statistiken', en: 'My Statistics' },
  'menu.profile': { de: 'Profil', en: 'Profile' },
  'menu.profileSub': { de: 'Einstellungen', en: 'Settings' },
  'menu.logout': { de: 'Abmelden', en: 'Log out' },
  'menu.logoutSub': { de: 'Vom Konto abmelden', en: 'Sign out of account' },

  // Profile
  'profile.title': { de: 'Mein Profil', en: 'My Profile' },
  'profile.edit': { de: 'Bearbeiten', en: 'Edit' },
  'profile.save': { de: 'Speichern', en: 'Save' },
  'profile.saving': { de: 'Speichern...', en: 'Saving...' },
  'profile.cancel': { de: 'Abbrechen', en: 'Cancel' },
  'profile.name': { de: 'Name', en: 'Name' },
  'profile.phone': { de: 'Telefon', en: 'Phone' },
  'profile.plate': { de: 'Kennzeichen', en: 'License Plate' },
  'profile.myPerformance': { de: 'Meine Leistung', en: 'My Performance' },
  'profile.notifications': { de: 'Benachrichtigungen', en: 'Notifications' },
  'profile.privacy': { de: 'Datenschutz', en: 'Privacy' },
  'profile.settings': { de: 'Einstellungen', en: 'Settings' },
  'profile.language': { de: 'Sprache', en: 'Language' },

  // Login
  'login.welcome': { de: 'Willkommen zurück', en: 'Welcome back' },
  'login.signIn': { de: 'Melden Sie sich an', en: 'Sign in to your account' },
  'login.register': { de: 'Konto erstellen', en: 'Create Account' },
  'login.registerSub': { de: 'Registrieren Sie sich', en: 'Register a new account' },
  'login.email': { de: 'E-Mail', en: 'Email' },
  /** First login field when ``VITE_DRIVER_API_PROVIDER=rest`` (maps to API ``username``). */
  'login.loginId': { de: 'Anmeldename', en: 'Username' },
  'login.loginIdHint': {
    de: 'Telefon, E-Mail oder Fahrercode — wie im Dispatcher angelegt (nicht zwingend eine E-Mail).',
    en: 'Phone, email, or driver code — same as saved in the dispatcher (not necessarily an email).',
  },
  'login.password': { de: 'Passwort', en: 'Password' },
  'login.fullName': { de: 'Vollständiger Name', en: 'Full Name' },
  'login.signInBtn': { de: 'Anmelden', en: 'Sign In' },
  'login.signingIn': { de: 'Anmeldung...', en: 'Signing in...' },
  'login.registerBtn': { de: 'Registrieren', en: 'Register' },
  'login.registering': { de: 'Registrierung...', en: 'Registering...' },
  'login.noAccount': { de: 'Noch kein Konto?', en: 'No account yet?' },
  'login.hasAccount': { de: 'Bereits ein Konto?', en: 'Already have an account?' },
  'login.fillAll': { de: 'Bitte alle Felder ausfüllen', en: 'Please fill in all fields' },
  'login.wrongCreds': { de: 'E-Mail oder Passwort falsch', en: 'Email or password incorrect' },
  'login.wrongCredsRest': { de: 'Benutzername oder Passwort falsch', en: 'Username or password incorrect' },
  'login.pwdMin': { de: 'Passwort muss mindestens 6 Zeichen lang sein', en: 'Password must be at least 6 characters' },
  'login.newAccount': { de: 'Neues Konto erstellen', en: 'Create new account' },
  'login.readyForTour': { de: 'Bereit für die Tour?', en: 'Ready for the tour?' },
  'login.startNow': { de: 'Jetzt anmelden und starten', en: 'Sign in and get started' },
  'login.driverApp': { de: 'Fahrer-App für Altöl-Sammlung', en: 'Driver app for used oil collection' },

  // WorkTime
  'workTime.title': { de: 'Arbeitszeit', en: 'Work Time' },
  'workTime.inBreak': { de: 'In Pause', en: 'On Break' },
  'workTime.working': { de: 'Arbeit läuft', en: 'Working' },
  'workTime.startedAt': { de: 'Gestartet um', en: 'Started at' },
  'workTime.break': { de: 'Pause', en: 'Break' },
  'workTime.min': { de: 'Min.', en: 'min.' },
  'workTime.notStarted': { de: 'Arbeit nicht gestartet', en: 'Work not started' },
  'workTime.odometer': { de: 'Kilometerstand', en: 'Odometer' },
  'workTime.startKm': { de: 'Start (km)', en: 'Start (km)' },
  'workTime.endKm': { de: 'Ende (km)', en: 'End (km)' },
  'workTime.driven': { de: 'Gefahren', en: 'Driven' },
  'workTime.start': { de: 'Arbeit starten', en: 'Start Work' },
  'workTime.startBreak': { de: 'Pause starten', en: 'Start Break' },
  'workTime.endBreak': { de: 'Pause beenden', en: 'End Break' },
  'workTime.end': { de: 'Arbeit beenden', en: 'End Work' },

  // Tour Plan
  'tourPlan.title': { de: 'Tourenplan', en: 'Tour Plan' },
  'tourPlan.daily': { de: 'Tages-Tourenplan', en: 'Daily Tour Plan' },
  'tourPlan.start': { de: 'Start', en: 'Start' },
  'tourPlan.stops': { de: 'Stopps', en: 'Stops' },
  'tourPlan.endApprox': { de: 'Ende ca.', en: 'End approx.' },
  'tourPlan.routeLog': { de: 'Fahrtenverlauf', en: 'Route Log' },
  'tourPlan.time': { de: 'Zeit', en: 'Time' },
  'tourPlan.customer': { de: 'Kunde', en: 'Customer' },
  'tourPlan.downloadPdf': { de: 'Plan als PDF herunterladen', en: 'Download plan as PDF' },

  // Expenses / Fuel
  'expenses.title': { de: 'Belege & Ausgaben', en: 'Receipts & Expenses' },
  'expenses.newReceipt': { de: 'Neuen Beleg erfassen', en: 'Add new receipt' },
  'expenses.amount': { de: 'Betrag (€)', en: 'Amount (€)' },
  'expenses.liters': { de: 'Liter', en: 'Liters' },
  'expenses.station': { de: 'Tankstelle', en: 'Gas station' },
  'expenses.photo': { de: 'Foto', en: 'Photo' },
  'expenses.save': { de: 'Speichern', en: 'Save' },
  'expenses.recentReceipts': { de: 'Letzte Belege', en: 'Recent Receipts' },
  'expenses.exportAll': { de: 'Alle Belege exportieren', en: 'Export all receipts' },
  'expenses.fuelTab': { de: 'Kraftstoff', en: 'Fuel' },
  'expenses.vehicleTab': { de: 'Fahrzeug', en: 'Vehicle' },
  'expenses.vehicleExpense': { de: 'Fahrzeugausgabe', en: 'Vehicle Expense' },
  'expenses.newVehicleExpense': { de: 'Neue Ausgabe erfassen', en: 'Add new expense' },
  'expenses.category': { de: 'Kategorie', en: 'Category' },
  'expenses.description': { de: 'Beschreibung', en: 'Description' },
  'expenses.descPlaceholder': { de: 'z.B. Glühbirne vorne links', en: 'e.g. Front left bulb' },
  'expenses.uploadReceipt': { de: 'Beleg hochladen', en: 'Upload receipt' },
  'expenses.photoUploaded': { de: 'Foto hinzugefügt', en: 'Photo added' },
  'expenses.recentVehicle': { de: 'Letzte Fahrzeugausgaben', en: 'Recent Vehicle Expenses' },
  'expenses.noVehicleExpenses': { de: 'Noch keine Ausgaben erfasst', en: 'No expenses recorded yet' },
  'expenses.totalFuel': { de: 'Kraftstoff gesamt', en: 'Fuel total' },
  'expenses.totalVehicle': { de: 'Fahrzeug gesamt', en: 'Vehicle total' },
  'expenses.cat.light': { de: 'Beleuchtung', en: 'Lighting' },
  'expenses.cat.battery': { de: 'Batterie', en: 'Battery' },
  'expenses.cat.wiper': { de: 'Scheibenwischer', en: 'Wipers' },
  'expenses.cat.washer': { de: 'Scheibenreiniger', en: 'Washer Fluid' },
  'expenses.cat.tire': { de: 'Reifen', en: 'Tires' },
  'expenses.cat.oil': { de: 'Motoröl', en: 'Engine Oil' },
  'expenses.cat.brake': { de: 'Bremsen', en: 'Brakes' },
  'expenses.cat.other': { de: 'Sonstiges', en: 'Other' },
  'expenses.miscTab': { de: 'Sonstiges', en: 'Misc' },
  'expenses.newMiscExpense': { de: 'Neue Ausgabe erfassen', en: 'Add new expense' },
  'expenses.totalMisc': { de: 'Sonstiges gesamt', en: 'Misc total' },
  'expenses.recentMisc': { de: 'Letzte Ausgaben', en: 'Recent expenses' },
  'expenses.noMiscExpenses': { de: 'Noch keine sonstigen Ausgaben', en: 'No misc expenses yet' },
  'expenses.vendor': { de: 'Geschäft / Anbieter', en: 'Vendor / Store' },
  'expenses.paymentMethod': { de: 'Zahlungsart', en: 'Payment method' },
  'expenses.payCash': { de: 'Bar', en: 'Cash' },
  'expenses.payCard': { de: 'Eigene Karte', en: 'Own card' },
  'expenses.payCompanyCard': { de: 'Firmenkarte', en: 'Company card' },
  'expenses.statusPending': { de: 'Wartet auf Freigabe', en: 'Pending approval' },
  'expenses.statusApproved': { de: 'Genehmigt', en: 'Approved' },
  'expenses.statusRejected': { de: 'Abgelehnt', en: 'Rejected' },
  'expenses.statusReimbursed': { de: 'Erstattet', en: 'Reimbursed' },
  'expenses.misc.cleaning': { de: 'Reinigung', en: 'Cleaning' },
  'expenses.misc.tools': { de: 'Werkzeug', en: 'Tools' },
  'expenses.misc.parking': { de: 'Parken', en: 'Parking' },
  'expenses.misc.toll': { de: 'Maut', en: 'Toll' },
  'expenses.misc.carwash': { de: 'Autowäsche', en: 'Car wash' },
  'expenses.misc.food': { de: 'Verpflegung', en: 'Food' },
  'expenses.misc.office': { de: 'Büromaterial', en: 'Office supplies' },
  'expenses.misc.safety': { de: 'Sicherheit/PSA', en: 'Safety/PPE' },
  'expenses.misc.other': { de: 'Sonstiges', en: 'Other' },
  'expenses.miscDescPlaceholder': { de: 'z.B. Microfasertücher 5er Pack', en: 'e.g. Microfiber cloths 5-pack' },
  'smartRoute.title': { de: 'KI Route Optimierer', en: 'AI Route Optimizer' },
  'smartRoute.subtitle': { de: 'Spart Zeit, Kraftstoff und CO₂', en: 'Saves time, fuel & CO₂' },
  'smartRoute.optimize': { de: 'Tour optimieren', en: 'Optimize tour' },
  'smartRoute.optimizing': { de: 'Berechne…', en: 'Computing…' },
  'smartRoute.apply': { de: 'Reihenfolge übernehmen', en: 'Apply order' },
  'leaderboard.title': { de: 'Bestenliste', en: 'Leaderboard' },
  'leaderboard.points': { de: 'Punkte', en: 'Points' },
  'leaderboard.level': { de: 'Stufe', en: 'Level' },
  'leaderboard.streak': { de: 'Serie', en: 'Streak' },
  'leaderboard.you': { de: 'Du', en: 'You' },
  'leaderboard.empty': { de: 'Noch keine Daten', en: 'No data yet' },

  // Leave Requests
  'leave.title': { de: 'Urlaub & Krankmeldung', en: 'Leave & Sick Report' },
  'leave.docMissing': { de: 'Dokument fehlt!', en: 'Document missing!' },
  'leave.docMissingSub': { de: 'Krankmeldung(en) ohne Nachweis. Bitte laden Sie die AU-Bescheinigung hoch.', en: 'Sick report(s) without proof. Please upload the medical certificate.' },
  'leave.uploadNow': { de: 'Jetzt hochladen', en: 'Upload now' },
  'leave.approved': { de: 'Genehmigt', en: 'Approved' },
  'leave.pending': { de: 'Ausstehend', en: 'Pending' },
  'leave.rejected': { de: 'Abgelehnt', en: 'Rejected' },
  'leave.sickDays': { de: 'Krankheitstage', en: 'Sick days' },
  'leave.newRequest': { de: 'Neuen Antrag stellen', en: 'Submit new request' },
  'leave.vacation': { de: 'Urlaub', en: 'Vacation' },
  'leave.sick': { de: 'Krankmeldung', en: 'Sick Report' },
  'leave.vacationNotice': { de: 'Urlaubsanträge müssen mindestens 2 Wochen im Voraus gestellt werden.', en: 'Vacation requests must be submitted at least 2 weeks in advance.' },
  'leave.sickNotice': { de: 'Bitte laden Sie die AU-Bescheinigung spätestens 3 Tage nach Krankmeldung hoch.', en: 'Please upload the medical certificate within 3 days of the sick report.' },
  'leave.from': { de: 'Von', en: 'From' },
  'leave.to': { de: 'Bis', en: 'To' },
  'leave.reason': { de: 'Grund', en: 'Reason' },
  'leave.optional': { de: '(optional)', en: '(optional)' },
  'leave.uploadCert': { de: 'AU-Bescheinigung hochladen', en: 'Upload medical certificate' },
  'leave.submit': { de: 'Antrag absenden', en: 'Submit request' },
  'leave.myRequests': { de: 'Meine Anträge', en: 'My Requests' },
  'leave.requestedOn': { de: 'Beantragt am', en: 'Requested on' },
  'leave.docUploaded': { de: 'Dokument hochgeladen ✓', en: 'Document uploaded ✓' },

  // Messages
  'messages.title': { de: 'Nachrichten', en: 'Messages' },
  'messages.dispatch': { de: 'Disposition', en: 'Dispatch' },
  'messages.placeholder': { de: 'Nachricht schreiben...', en: 'Write a message...' },

  // Inventory
  'inventory.title': { de: 'Fahrzeug-Lager', en: 'Vehicle Storage' },
  'inventory.oilTank': { de: 'Öltank', en: 'Oil Tank' },
  'inventory.capacityLeft': { de: 'Noch {amount} kg Kapazität verfügbar', en: '{amount} kg capacity remaining' },
  'inventory.containers': { de: 'Behälter', en: 'Containers' },
  'inventory.bin': { de: 'Mülltonne', en: 'Bin' },
  'inventory.barrel60': { de: 'Fass 60 KG', en: 'Barrel 60 KG' },
  'inventory.barrel30': { de: 'Fass 30 KG', en: 'Barrel 30 KG' },
  'inventory.empty': { de: 'Leer', en: 'Empty' },
  'inventory.full': { de: 'Voll', en: 'Full' },
  'inventory.productsOnTruck': { de: 'Waren im Fahrzeug', en: 'Products on truck' },

  // Performance
  'perf.title': { de: 'Meine Leistung', en: 'My Performance' },
  'perf.totalCollected': { de: 'Gesamt gesammelt', en: 'Total collected' },
  'perf.visitsCompleted': { de: 'Besuche abgeschlossen', en: 'Visits completed' },
  'perf.ranking': { de: 'Ranking', en: 'Ranking' },
  'perf.of': { de: 'von', en: 'of' },
  'perf.streak': { de: 'Streak', en: 'Streak' },
  'perf.best': { de: 'Best', en: 'Best' },
  'perf.points': { de: 'Punkte', en: 'Points' },
  'perf.level': { de: 'Level', en: 'Level' },
  'perf.week': { de: 'Woche', en: 'Week' },
  'perf.month': { de: 'Monat', en: 'Month' },
  'perf.year': { de: 'Jahr', en: 'Year' },
  'perf.thisWeek': { de: 'Diese Woche', en: 'This Week' },
  'perf.thisMonth': { de: 'Dieser Monat', en: 'This Month' },
  'perf.thisYear': { de: 'Dieses Jahr', en: 'This Year' },
  'perf.oilKg': { de: 'kg Öl', en: 'kg Oil' },
  'perf.avgPerDay': { de: 'Ø kg/Tag', en: 'Ø kg/Day' },
  'perf.avgPerMonth': { de: 'Ø kg/Monat', en: 'Ø kg/Month' },
  'perf.showHistory': { de: 'Verlauf anzeigen', en: 'Show History' },
  'perf.badges': { de: 'Abzeichen', en: 'Badges' },

  // Morning Flow
  'morning.title': { de: 'Tagesstart', en: 'Day Start' },
  'morning.discharge': { de: 'Behälter entleeren', en: 'Empty containers' },
  'morning.dischargeSub': { de: 'Bitte entleeren Sie alle vollen Behälter in den Tank.', en: 'Please empty all full containers into the tank.' },
  'morning.fullBins': { de: 'Volle Mülltonnen', en: 'Full bins' },
  'morning.fullBarrels60': { de: 'Volle Fässer (60 KG)', en: 'Full barrels (60 KG)' },
  'morning.fullBarrels30': { de: 'Volle Fässer (30 KG)', en: 'Full barrels (30 KG)' },
  'morning.estimated': { de: 'Geschätzt', en: 'Estimated' },
  'morning.usedOil': { de: 'Altöl', en: 'used oil' },
  'morning.dischargeDone': { de: 'Entleerung abgeschlossen', en: 'Discharge complete' },
  'morning.loadVehicle': { de: 'Fahrzeug beladen', en: 'Load vehicle' },
  'morning.loadSub': { de: 'Folgende Behälter und Waren bitte mitnehmen:', en: 'Please take the following containers and goods:' },
  'morning.containers': { de: 'Behälter', en: 'Containers' },
  'morning.goods': { de: 'Waren', en: 'Goods' },
  'morning.allLoaded': { de: 'Alles geladen', en: 'All loaded' },
  'morning.scanContainers': { de: 'Behälter scannen', en: 'Scan containers' },
  'morning.scanned': { de: 'Behälter gescannt', en: 'containers scanned' },
  'morning.scanQr': { de: 'QR-Code scannen', en: 'Scan QR code' },
  'morning.markAllScanned': { de: 'Alle als gescannt markieren', en: 'Mark all as scanned' },
  'morning.toRoute': { de: 'Weiter zur Route', en: 'Continue to route' },
  'morning.yourRoute': { de: 'Deine Route heute', en: 'Your route today' },
  'morning.stopsOil': { de: 'Stopps · ca. {oil} kg Öl erwartet', en: 'Stops · approx. {oil} kg oil expected' },
  'morning.moreStops': { de: 'weitere Stopps', en: 'more stops' },
  'morning.startTour': { de: 'Tour starten 🚛', en: 'Start tour 🚛' },
  'morning.pieces': { de: 'Stück', en: 'pieces' },

  // Scanner
  'scan.title': { de: 'Scanner', en: 'Scanner' },
  'scan.before': { de: 'Vorher', en: 'Before' },
  'scan.after': { de: 'Nachher', en: 'After' },
  'scan.scanQr': { de: 'QR-Code scannen', en: 'Scan QR code' },
  'scan.holdQr': { de: 'Halten Sie den QR-Code des Behälters in den Rahmen', en: 'Hold the container QR code in the frame' },
  'scan.simulate': { de: 'Simulieren', en: 'Simulate' },
  'scan.containerRecognized': { de: 'Behälter erkannt', en: 'Container recognized' },
  'scan.photoBefore': { de: 'Foto VOR der Abholung', en: 'Photo BEFORE pickup' },
  'scan.photoAfter': { de: 'Foto NACH der Abholung', en: 'Photo AFTER pickup' },
  'scan.docBefore': { de: 'Dokumentieren Sie den Zustand vorher', en: 'Document the condition before' },
  'scan.docAfter': { de: 'Dokumentieren Sie den Zustand nachher', en: 'Document the condition after' },
  'scan.takePhoto': { de: 'Foto aufnehmen', en: 'Take photo' },
  'scan.done': { de: 'Fertig!', en: 'Done!' },
  'scan.documented': { de: 'Behälter {id} dokumentiert', en: 'Container {id} documented' },
  'scan.next': { de: 'Nächster', en: 'Next' },
  'scan.back': { de: 'Zurück', en: 'Back' },

  // Visit Navigation
  'visitNav.title': { de: 'Navigation', en: 'Navigation' },
  'visitNav.arrivalTime': { de: 'Ankunftszeit', en: 'Arrival time' },
  'visitNav.arrived': { de: 'Ich bin angekommen', en: 'I have arrived' },
  'visitNav.expectedOil': { de: 'Erwartetes Öl', en: 'Expected oil' },
  'visitNav.navigate': { de: 'Navigieren', en: 'Navigate' },

  // Visit Detail
  'visit.notFound': { de: 'Nicht gefunden', en: 'Not found' },
  'visit.notFoundMsg': { de: 'Besuch nicht gefunden.', en: 'Visit not found.' },
  'visit.emptyContainers': { de: 'Leer – Behälter', en: 'Empty Containers' },
  'visit.weight': { de: 'Gewicht', en: 'Weight' },
  'visit.totalKg': { de: 'Gesamt (kg)', en: 'Total (kg)' },
  'visit.tareKg': { de: 'Tara (kg)', en: 'Tare (kg)' },
  'visit.netOil': { de: 'Netto: {amount} kg Öl', en: 'Net: {amount} kg oil' },
  'visit.payment': { de: 'Zahlungsmethode', en: 'Payment Method' },
  'visit.cash': { de: 'Bar', en: 'Cash' },
  'visit.transaction': { de: 'Transaktion', en: 'Transaction' },
  'visit.other': { de: 'Andere', en: 'Other' },
  'visit.paymentAmount': { de: 'Zahlung', en: 'Payment' },
  'visit.products': { de: 'Waren', en: 'Products' },
  'visit.feedbackMedia': { de: 'Feedback & Medien', en: 'Feedback & Media' },
  'visit.photo': { de: 'Foto', en: 'Photo' },
  'visit.voiceNote': { de: 'Sprachnachricht', en: 'Voice Note' },
  'visit.note': { de: 'Notiz', en: 'Note' },
  'visit.notePlaceholder': { de: 'Notiz für Disposition...', en: 'Note for dispatch...' },
  'visit.confirm': { de: 'Bestätigen ✓', en: 'Confirm ✓' },
  'visit.contractPrice': { de: 'Vertragspreis', en: 'Contract Price' },

  // Route Map
  'route.title': { de: 'Route', en: 'Route' },
  'route.order': { de: 'Reihenfolge', en: 'Order' },
  'route.completed': { de: 'erledigt', en: 'completed' },

  // Morning Popup
  'popup.goodMorning': { de: 'Guten Morgen! ☀️', en: 'Good morning! ☀️' },
  'popup.dayOverview': { de: 'Dein Tag im Überblick', en: 'Your day at a glance' },
  'popup.cloudy': { de: 'Bewölkt', en: 'Cloudy' },
  'popup.yourCities': { de: 'Deine Städte heute', en: 'Your cities today' },
  'popup.driveTime': { de: 'Fahrzeit', en: 'Drive time' },
  'popup.oilExpected': { de: 'kg Öl erw.', en: 'kg oil exp.' },
  'popup.dayPlan': { de: 'Tagesplan', en: 'Day Plan' },
  'popup.departure': { de: 'Abfahrt vom Lager', en: 'Departure from depot' },
  'popup.pause': { de: 'Pause', en: 'Break' },
  'popup.minutes': { de: 'Minuten', en: 'minutes' },
  'popup.end': { de: 'Ende', en: 'End' },
  'popup.returnDepot': { de: 'Rückkehr zum Lager', en: 'Return to depot' },
  'popup.goodTrip': { de: '🚛 Gute Fahrt & sichere Reise!', en: '🚛 Have a safe trip!' },
  'popup.letsGo': { de: 'Los geht\'s! 🚀', en: 'Let\'s go! 🚀' },
  'popup.moreStops': { de: 'weitere Stopps', en: 'more stops' },

  // PIN
  'pin.setup': { de: 'PIN festlegen', en: 'Set PIN' },
  'pin.confirm': { de: 'PIN bestätigen', en: 'Confirm PIN' },
  'pin.enter': { de: 'PIN eingeben', en: 'Enter PIN' },
  'pin.choose4': { de: 'Wähle einen 4-stelligen PIN', en: 'Choose a 4-digit PIN' },
  'pin.reenter': { de: 'Bitte erneut eingeben', en: 'Please re-enter' },
  'pin.quickAccess': { de: 'Schneller Zugriff', en: 'Quick access' },
  'pin.mismatch': { de: 'PINs stimmen nicht überein', en: 'PINs do not match' },
  'pin.wrong': { de: 'Falscher PIN', en: 'Wrong PIN' },
  'pin.success': { de: 'Erfolgreich!', en: 'Success!' },
  'pin.usePassword': { de: 'Mit Passwort anmelden', en: 'Sign in with password' },
  'pin.skip': { de: 'Überspringen', en: 'Skip' },

  // General
  'driver': { de: 'Fahrer', en: 'Driver' },
  'saved': { de: 'Profil gespeichert', en: 'Profile saved' },
  'saveError': { de: 'Fehler beim Speichern', en: 'Error saving' },
  'start': { de: 'Start', en: 'Start' },
  'cancel': { de: 'Abbrechen', en: 'Cancel' },

  // Break page
  'break.title': { de: 'Pflichtpause', en: 'Mandatory Break' },
  'break.subtitle': { de: '60 Minuten gesetzliche Ruhezeit', en: '60 minutes legal rest time' },
  'break.remaining': { de: 'Verbleibend', en: 'Remaining' },
  'break.paused': { de: 'Pausiert', en: 'Paused' },
  'break.elapsed': { de: 'vergangen', en: 'elapsed' },
  'break.done': { de: 'Pause fertig!', en: 'Break complete!' },
  'break.resume': { de: 'Fortsetzen', en: 'Resume' },
  'break.pause': { de: 'Pausieren', en: 'Pause' },
  'break.remindMe': { de: 'Erinnere mich', en: 'Remind me' },
  'break.reminderOff': { de: 'Erinnerung aus', en: 'Reminder off' },
  'break.endEarly': { de: 'Pause vorzeitig beenden', en: 'End break early' },
  'break.continue': { de: 'Weiterfahren', en: 'Continue driving' },
  'break.endConfirmTitle': { de: 'Pause beenden?', en: 'End break?' },
  'break.endConfirmSub': { de: 'Du hast erst {min} von 60 Minuten geruht.', en: 'You have only rested {min} of 60 minutes.' },
  'break.endWarning': { de: '⚠️ Die gesetzliche Ruhezeit beträgt 60 Minuten. Ein vorzeitiges Beenden wird dokumentiert.', en: '⚠️ Legal rest time is 60 minutes. Early termination will be documented.' },
  'break.keepResting': { de: 'Weiter ruhen', en: 'Keep resting' },
  'break.endAnyway': { de: 'Trotzdem beenden', en: 'End anyway' },
  'break.tipTitle': { de: 'Zeit für dich!', en: 'Time for you!' },
  'break.tipText': { de: 'Nutze die Pause zum Essen, Trinken oder Entspannen. Du wirst benachrichtigt, wenn es weitergeht.', en: 'Use the break to eat, drink, or relax. You will be notified when it\'s time to continue.' },
  'break.reminderSet': { de: 'Erinnerung gesetzt — Du wirst benachrichtigt, wenn die Pause vorbei ist.', en: 'Reminder set — You will be notified when the break is over.' },
  'break.reminderRemoved': { de: 'Erinnerung entfernt', en: 'Reminder removed' },
  'break.completeToast': { de: 'Pause beendet! Du kannst jetzt weiterfahren.', en: 'Break complete! You can continue driving now.' },
  'break.movementDetected': { de: '🚨 Fahrzeugbewegung während Pause!', en: '🚨 Vehicle movement during break!' },
  'break.movementDesc': { de: 'Das Fahrzeug hat sich {m} m vom Pausenort entfernt. Dies wurde dokumentiert und an die Zentrale gemeldet.', en: 'The vehicle moved {m} m from the break location. This has been logged and reported to dispatch.' },
  'break.monitorActive': { de: 'GPS-Überwachung aktiv', en: 'GPS monitoring active' },
  'break.distanceFromStart': { de: 'Entfernung vom Pausenort', en: 'Distance from break start' },
  'break.movementBannerTitle': { de: 'Bewegung erkannt', en: 'Movement detected' },
  'break.movementBannerText': { de: 'Bitte gib einen Grund an, falls du das Fahrzeug bewegen musstest.', en: 'Please provide a reason if you had to move the vehicle.' },

  // Route page extras
  'route.mandatoryBreak': { de: 'Pflichtpause', en: 'Mandatory Break' },
  'route.legalRest': { de: '{min} Min gesetzliche Ruhezeit', en: '{min} min legal rest time' },
  'route.startBreak': { de: 'Starten', en: 'Start' },
  'route.onSite': { de: 'Vor Ort', en: 'On site' },
  'route.departure': { de: 'Abfahrt', en: 'Departure' },
  'route.arrival': { de: 'Ankunft', en: 'Arrival' },
  'route.warehouse': { de: 'Lager', en: 'Warehouse' },
  'route.returnToWarehouse': { de: 'Zurück zum Lager', en: 'Return to warehouse' },

  // GPS tracking
  'gps.active': { de: 'GPS aktiv', en: 'GPS active' },
  'gps.toastTitle': { de: '📍 GPS-Tracking aktiv', en: '📍 GPS tracking active' },
  'gps.toastDesc': { de: 'Ihr Standort und Ihre Zeit werden vom Disponenten / KI-Agenten überwacht, um das Dispatching-System des Unternehmens zu optimieren.', en: 'Your location and time are being monitored by the dispatcher / AI agent to optimize the company\'s dispatching system.' },
  'gps.trackingInfo': { de: 'GPS-Tracking aktiv', en: 'GPS tracking active' },
  'gps.trackingInfoSub': { de: 'Standort, Geschwindigkeit und Stopps werden erfasst und im Aktivitätsbericht dokumentiert.', en: 'Location, speed, and stops are recorded and documented in the activity report.' },

  // Container Scanner
  'scanner.pickup': { de: 'Abholung', en: 'Pickup' },
  'scanner.pickupSub': { de: '(vom Kunden nehmen)', en: '(take from customer)' },
  'scanner.dropoff': { de: 'Abgabe', en: 'Drop-off' },
  'scanner.dropoffSub': { de: '(dem Kunden geben)', en: '(give to customer)' },
  'scanner.noPickup': { de: 'Keine Behälter abgeholt', en: 'No containers picked up' },
  'scanner.noDropoff': { de: 'Keine Behälter abgegeben', en: 'No containers dropped off' },
  'scanner.scanPickup': { de: 'Behälter scannen (Abholung)', en: 'Scan container (Pickup)' },
  'scanner.scanDropoff': { de: 'Behälter scannen (Abgabe)', en: 'Scan container (Drop-off)' },
  'scanner.otherContainers': { de: 'Sonstige Behälter', en: 'Other containers' },
  'scanner.noQr': { de: '(ohne QR-Code)', en: '(without QR code)' },
  'scanner.cameraPickupLabel': { de: '📤 Abholung — vom Kunden nehmen', en: '📤 Pickup — take from customer' },
  'scanner.cameraDropoffLabel': { de: '📥 Abgabe — dem Kunden geben', en: '📥 Drop-off — give to customer' },
  'scanner.cancel': { de: 'Abbrechen', en: 'Cancel' },

  // Tour Overview extras
  'tour.departureFrom': { de: 'Abfahrt', en: 'Departure' },
  'tour.arrivalAt': { de: 'Ankunft', en: 'Arrival' },
  'tour.onSite': { de: 'Vor Ort', en: 'On site' },
  'tour.mandatoryBreak': { de: 'Pflichtpause', en: 'Mandatory Break' },
  'tour.legalRest': { de: '60 Min gesetzliche Ruhezeit', en: '60 min legal rest time' },

  // Visit nav
  'visitNav.arrivalTimeLabel': { de: 'Ankunftszeit', en: 'Arrival time' },

  // Visit source badges
  'source.scheduled': { de: 'Terminiert', en: 'Scheduled' },
  'source.called': { de: 'Angerufen', en: 'Called in' },
  'source.auto_planned': { de: 'Auto-Plan', en: 'Auto-planned' },
  'source.prospect': { de: 'Interessent', en: 'Prospect' },

  // VisitDetail
  'visit.usedOil': { de: 'Altöl', en: 'Used Oil' },
  'visit.collected': { de: 'Gesammelt (kg)', en: 'Collected (kg)' },
  'visit.invoiced': { de: 'Fakturiert (kg)', en: 'Invoiced (kg)' },
  'visit.kgCollected': { de: 'kg gesammelt', en: 'kg collected' },
  'visit.kgInvoiced': { de: 'kg fakturiert', en: 'kg invoiced' },
  'visit.companyContainers': { de: 'Firmenbehälter', en: 'Company Containers' },
  'visit.otherContainers': { de: 'Sonstige Behälter', en: 'Other Containers' },
  'visit.summary': { de: 'Zusammenfassung', en: 'Summary' },
  'visit.customerNotMet': { de: 'Kunde nicht angetroffen', en: 'Customer not met' },
  'visit.dormantWarning': { de: 'Kunde verliert Interesse — bitte aktiv ansprechen', en: 'Customer losing interest — please actively engage' },
  'visit.bankUpdate': { de: 'Bankverbindung aktualisieren', en: 'Update bank details' },
  'visit.bankUpdateSub': { de: 'Bitte Kundendaten vor Ort erfassen', en: 'Please collect customer data on site' },
  'visit.containersAtCustomer': { de: 'Behälter beim Kunden', en: 'Containers at customer' },
  'visit.pickedUp': { de: 'Abgeholt', en: 'Picked up' },
  'visit.containersRemain': { de: 'Behälter verbleiben beim Kunden.', en: 'containers remain at customer.' },
  'visit.pickupNextVisit': { de: 'Bitte beim nächsten Besuch abholen.', en: 'Please collect on next visit.' },

  // WorkTime extras
  'wt.dayComplete': { de: 'Feierabend!', en: 'Day complete!' },
  'wt.kmEstimated': { de: 'km geschätzt', en: 'km estimated' },
  'wt.endWorkDay': { de: 'Arbeitstag beenden', en: 'End Work Day' },
  'wt.minBreak': { de: 'Min. Pause', en: 'min break' },
  'wt.kmAuto': { de: 'Kilometer (automatisch)', en: 'Kilometers (auto)' },
  'wt.kmChanged': { de: 'Geändert', en: 'Changed' },
  'wt.kmCalcRoute': { de: 'km berechnet aus Routendaten', en: 'km calculated from route data' },
  'wt.dailyComment': { de: 'Tageskommentar', en: 'Daily Comment' },
  'wt.optional': { de: 'Optional', en: 'Optional' },
  'wt.commentPlaceholder': { de: 'Besondere Vorkommnisse, Probleme, Anmerkungen...', en: 'Special incidents, problems, notes...' },
  'wt.stopRecording': { de: 'Aufnahme stoppen...', en: 'Stop recording...' },
  'wt.recordVoice': { de: 'Sprachnotiz aufnehmen', en: 'Record voice note' },
  'wt.completeDay': { de: 'Tag abschließen', en: 'Complete Day' },
  'wt.cancel': { de: 'Abbrechen', en: 'Cancel' },
  'wt.deviationDetected': { de: 'Abweichung erkannt', en: 'Deviation detected' },
  'wt.yourValue': { de: 'Dein Wert', en: 'Your value' },
  'wt.calculated': { de: 'Berechnet', en: 'Calculated' },
  'wt.deviationReason': { de: 'Bitte gib einen kurzen Grund für die Abweichung an:', en: 'Please provide a brief reason for the deviation:' },
  'wt.deviationPlaceholder': { de: 'z.B. Umleitung, Privatfahrt, Tankstelle...', en: 'e.g. Detour, private trip, gas station...' },
  'wt.back': { de: 'Zurück', en: 'Back' },
  'wt.confirm': { de: 'Bestätigen', en: 'Confirm' },
  'wt.thankYou': { de: 'Vielen Dank für deinen Einsatz!', en: 'Thank you for your hard work!' },
  'wt.dataSubmitted': { de: 'Deine Daten wurden erfolgreich übermittelt.', en: 'Your data has been submitted successfully.' },
  'wt.dayInNumbers': { de: 'Dein Tag in Zahlen', en: 'Your Day in Numbers' },
  'wt.visitsDone': { de: 'Besuche erledigt', en: 'Visits done' },
  'wt.oilCollected': { de: 'Öl gesammelt', en: 'Oil collected' },
  'wt.kmDriven': { de: 'km gefahren', en: 'km driven' },
  'wt.predicted': { de: 'Vorhergesagt', en: 'Predicted' },
  'wt.actual': { de: 'Tatsächlich', en: 'Actual' },
  'wt.kmDeviation': { de: 'km-Abweichung', en: 'km deviation' },
  'wt.visitsCompleted': { de: 'von {total} Besuchen erfolgreich abgeschlossen!', en: 'of {total} visits successfully completed!' },
  'wt.eveningGreeting': { de: 'Schönen Feierabend!', en: 'Have a great evening!' },
  'wt.nightGreeting': { de: 'Gute Nacht & erholsame Ruhe!', en: 'Good night & rest well!' },
  'wt.voiceSaved': { de: 'Sprachnotiz gespeichert', en: 'Voice note saved' },

  // Geofence / Start location
  'geo.checking': { de: 'Standort wird geprüft...', en: 'Checking location...' },
  'geo.permissionDenied': { de: 'GPS-Berechtigung erforderlich. Bitte aktiviere den Standortzugriff in den Einstellungen.', en: 'GPS permission required. Please enable location access in settings.' },
  'geo.unavailable': { de: 'Standort nicht verfügbar. Bitte prüfe dein GPS.', en: 'Location unavailable. Please check your GPS.' },
  'geo.atDepot': { de: 'Du bist am Lager – Start freigegeben', en: 'You are at the depot – start approved' },
  'geo.notAtDepot': { de: 'Du bist nicht am Lager', en: 'You are not at the depot' },
  'geo.distanceFromDepot': { de: 'Entfernung zum Lager', en: 'Distance from depot' },
  'geo.preloadedActive': { de: 'Fahrzeug von gestern beladen – Start von zu Hause erlaubt', en: 'Vehicle preloaded yesterday – home start permitted' },
  'geo.mustGoToDepot': { de: 'Dein Fahrzeug ist nicht beladen. Bitte fahre zuerst zum Lager.', en: 'Your vehicle is not loaded. Please drive to the depot first.' },
  'geo.navigateToDepot': { de: 'Zum Lager navigieren', en: 'Navigate to depot' },
  'geo.emergencyStart': { de: 'Notfall-Start', en: 'Emergency start' },
  'geo.emergencyTitle': { de: 'Notfall-Start mit Begründung', en: 'Emergency start with reason' },
  'geo.emergencyDesc': { de: 'Erkläre kurz, warum du außerhalb des Lagers startest. Diese Meldung wird an den Disponenten weitergeleitet.', en: 'Briefly explain why you are starting outside the depot. This will be forwarded to dispatch.' },
  'geo.emergencyPlaceholder': { de: 'z.B. Sammeltour vom Disponenten gestern direkt zugeteilt...', en: 'e.g. Collection route assigned by dispatch yesterday...' },
  'geo.emergencyMin': { de: 'Mindestens 20 Zeichen', en: 'At least 20 characters' },
  'geo.confirmStart': { de: 'Trotzdem starten', en: 'Start anyway' },
  'wt.preloadedQuestion': { de: 'Hast du saubere Behälter für morgen ins Fahrzeug geladen?', en: 'Did you load clean containers for tomorrow into the vehicle?' },
  'wt.preloadedYes': { de: 'Ja, Fahrzeug ist beladen', en: 'Yes, vehicle is loaded' },
  'wt.preloadedHint': { de: 'Wenn ja, darfst du morgen direkt von zu Hause starten.', en: 'If yes, you may start from home tomorrow.' },

  // Performance extras
  'perf.overview': { de: 'Übersicht', en: 'Overview' },
  'perf.workTime': { de: 'Arbeitszeit', en: 'Work Time' },
  'perf.successRate': { de: 'Erfolgsquote', en: 'Success Rate' },
  'perf.activity': { de: 'Aktivität', en: 'Activity' },
  'perf.regularHours': { de: 'Regelstunden', en: 'Regular hours' },
  'perf.overtime': { de: 'Überstunden', en: 'Overtime' },
  'perf.totalKm': { de: 'km gesamt', en: 'total km' },
  'perf.workLog': { de: 'Arbeitszeitprotokoll', en: 'Work time log' },
  'perf.loginHistory': { de: 'App-Anmeldeverlauf', en: 'App login history' },
  'perf.monthlyRate': { de: 'Monatliche Abschlussquote', en: 'Monthly completion rate' },
  'perf.completed': { de: 'erledigt', en: 'completed' },
  'perf.skipped': { de: 'übersprungen', en: 'skipped' },
  'perf.total': { de: 'gesamt', en: 'total' },
  'perf.yearOverview': { de: 'Jahresübersicht', en: 'Year overview' },
  'perf.absences': { de: 'Meine Abwesenheiten', en: 'My absences' },
  'perf.leaveVacation': { de: 'Urlaub', en: 'Vacation' },
  'perf.leaveSick': { de: 'Krank', en: 'Sick' },
  'perf.leaveHourly': { de: 'Stundenweise', en: 'Hourly' },
  'perf.gpsLog': { de: 'GPS-Aktivitätsprotokoll', en: 'GPS activity log' },
  'perf.gpsLogSub': { de: 'Dein Standort, Geschwindigkeit und Stopps werden automatisch erfasst. Langsame Fahrten, Leerlaufzeiten und ungeplante Stopps werden hier dokumentiert.', en: 'Your location, speed, and stops are automatically recorded. Slow driving, idle times, and unplanned stops are documented here.' },
  'perf.driveTime': { de: 'Fahrzeit', en: 'Drive time' },
  'perf.slow': { de: 'Langsam', en: 'Slow' },
  'perf.idle': { de: 'Leerlauf', en: 'Idle' },
  'perf.weekActivity': { de: 'Wochenaktivität (Minuten)', en: 'Weekly activity (minutes)' },
  'perf.driving': { de: 'Fahren', en: 'Driving' },
  'perf.todayTimeline': { de: 'Heutige Aktivität (Timeline)', en: "Today's activity (timeline)" },

  // MorningPopup
  'mp.goodMorning': { de: 'Guten Morgen! ☀️', en: 'Good morning! ☀️' },
  'mp.dayOverview': { de: 'Dein Tag im Überblick', en: 'Your day at a glance' },
  'mp.cloudy': { de: 'Bewölkt', en: 'Cloudy' },
  'mp.yourCities': { de: 'Deine Städte heute', en: 'Your cities today' },
  'mp.visits': { de: 'Besuche', en: 'Visits' },
  'mp.driveTime': { de: 'Fahrzeit', en: 'Drive time' },
  'mp.oilExp': { de: 'kg Öl erw.', en: 'kg oil exp.' },
  'mp.dayPlan': { de: 'Tagesplan', en: 'Day Plan' },
  'mp.departure': { de: 'Abfahrt vom Lager', en: 'Departure from depot' },
  'mp.break': { de: 'Pause', en: 'Break' },
  'mp.minutes': { de: 'Minuten', en: 'minutes' },
  'mp.end': { de: 'Ende', en: 'End' },
  'mp.returnDepot': { de: 'Rückkehr zum Lager', en: 'Return to depot' },
  'mp.moreStops': { de: 'weitere Stopps', en: 'more stops' },
  'mp.goodTrip': { de: '🚛 Gute Fahrt & sichere Reise!', en: '🚛 Have a safe trip!' },
  'mp.letsGo': { de: "Los geht's! 🚀", en: "Let's go! 🚀" },
  'mp.stops': { de: 'Stopps', en: 'Stops' },

  // FailedVisitDialog
  'failed.notPresent': { de: 'Kunde nicht angetroffen', en: 'Customer not present' },
  'failed.closed': { de: 'Geschäft geschlossen', en: 'Business closed' },
  'failed.refused': { de: 'Kunde hat abgelehnt', en: 'Customer refused' },
  'failed.noAccess': { de: 'Kein Zugang möglich', en: 'No access possible' },
  'failed.other': { de: 'Sonstiges', en: 'Other' },
  'failed.title': { de: 'Besuch nicht möglich', en: 'Visit not possible' },
  'failed.selectReason': { de: 'Grund auswählen', en: 'Select reason' },
  'failed.additionalInfo': { de: 'Zusätzliche Informationen', en: 'Additional information' },
  'failed.photo': { de: 'Foto', en: 'Photo' },
  'failed.voiceNote': { de: 'Sprachnotiz', en: 'Voice note' },
  'failed.placeholder': { de: 'Beschreibung oder Hinweis für die Disposition...', en: 'Description or note for dispatch...' },
  'failed.submit': { de: 'Besuch als nicht erfolgreich melden', en: 'Report visit as unsuccessful' },

  // BankUpdateForm
  'bank.title': { de: 'Bankverbindung', en: 'Bank Details' },
  'bank.customerNo': { de: 'KUNDEN-NR', en: 'CUSTOMER NO' },
  'bank.businessName': { de: 'Name des Betriebes', en: 'Business name' },
  'bank.email': { de: 'E-Mail', en: 'Email' },
  'bank.ownerName': { de: 'Name des Inhabers/Betreibers', en: 'Owner/operator name' },
  'bank.bankDetails': { de: 'Bankverbindung', en: 'Bank details' },
  'bank.institution': { de: 'Kreditinstitut', en: 'Bank name' },
  'bank.accountHolder': { de: 'Kontoinhaber', en: 'Account holder' },
  'bank.toSignature': { de: 'Weiter zur Unterschrift', en: 'Continue to signature' },
  'bank.updated': { de: 'Bankverbindung aktualisiert', en: 'Bank details updated' },
  'bank.updatedSub': { de: 'Die neuen Bankdaten wurden erfolgreich erfasst.', en: 'New bank details have been recorded successfully.' },
  'bank.close': { de: 'Schließen', en: 'Close' },

  // VisitSummary
  'summary.title': { de: 'Zusammenfassung', en: 'Summary' },
  'summary.signature': { de: 'Kundenunterschrift', en: 'Customer signature' },
  'summary.receipts': { de: 'Belege', en: 'Receipts' },
  'summary.feedbackMedia': { de: 'Feedback & Medien', en: 'Feedback & Media' },
  'summary.oilCollected': { de: 'Altöl gesammelt', en: 'Used oil collected' },
  'summary.pickedUp': { de: 'Abgeholte Behälter', en: 'Picked up containers' },
  'summary.droppedOff': { de: 'Abgegebene Behälter', en: 'Dropped off containers' },
  'summary.otherContainers': { de: 'Sonstige Behälter', en: 'Other containers' },
  'summary.soldProducts': { de: 'Verkaufte Waren', en: 'Sold products' },
  'summary.total': { de: 'Gesamt', en: 'Total' },
  'summary.toSignature': { de: 'Weiter zur Unterschrift', en: 'Continue to signature' },
  'summary.signatureSaved': { de: 'Unterschrift gespeichert', en: 'Signature saved' },
  'summary.resignBtn': { de: 'Erneut unterschreiben', en: 'Sign again' },
  'summary.toReceipts': { de: 'Weiter zu Belegen', en: 'Continue to receipts' },
  'summary.toFeedback': { de: 'Weiter zu Feedback', en: 'Continue to feedback' },
  'summary.photoBtn': { de: 'Foto', en: 'Photo' },
  'summary.voiceBtn': { de: 'Sprache', en: 'Voice' },
  'summary.notePlaceholder': { de: 'Notiz für Disposition...', en: 'Note for dispatch...' },
  'summary.confirmBtn': { de: 'Bestätigen ✓', en: 'Confirm ✓' },

  // SignaturePad
  'sig.clear': { de: 'Löschen', en: 'Clear' },
  'sig.confirm': { de: 'Bestätigen', en: 'Confirm' },

  // Common
  'common.save': { de: 'Speichern', en: 'Save' },
  'common.cancel': { de: 'Abbrechen', en: 'Cancel' },
  'common.notes': { de: 'Notizen', en: 'Notes' },
  'common.other': { de: 'Sonstiges', en: 'Other' },
  'common.add': { de: 'Hinzufügen', en: 'Add' },
  'common.description': { de: 'Beschreibung', en: 'Description' },

  // Delivery Signature dialog
  'sig.dialogTitle': { de: 'Digitale Unterschrift', en: 'Digital Signature' },
  'sig.purpose': { de: 'Zweck', en: 'Purpose' },
  'sig.purpose.fresh': { de: 'Frischware-Lieferung', en: 'Fresh-food delivery' },
  'sig.purpose.oil': { de: 'Öl-Abholung', en: 'Oil collection' },
  'sig.purpose.bin': { de: 'Behälter-Übergabe', en: 'Bin handover' },
  'sig.purpose.damage': { de: 'Schaden-Bestätigung', en: 'Damage acknowledgement' },
  'sig.signerName': { de: 'Name (Empfänger)', en: 'Signer name' },
  'sig.signerRole': { de: 'Funktion', en: 'Role' },
  'sig.rolePlaceholder': { de: 'z.B. Küchenchef', en: 'e.g. Head chef' },
  'sig.items': { de: 'Gelieferte Artikel', en: 'Delivered items' },
  'sig.itemLabel': { de: 'Artikel', en: 'Item' },
  'sig.total': { de: 'Summe', en: 'Total' },
  'sig.padLabel': { de: 'Unterschrift hier', en: 'Sign here' },
  'sig.captured': { de: 'Unterschrift erfasst', en: 'Signature captured' },
  'sig.required': { de: 'Unterschrift erforderlich', en: 'Signature required' },
  'sig.nameRequired': { de: 'Name erforderlich', en: 'Name required' },
  'sig.gpsError': { de: 'GPS-Fehler', en: 'GPS error' },
  'sig.saved': { de: 'Unterschrift gespeichert', en: 'Signature saved' },
  'sig.signFreshFood': { de: 'Lieferung unterschreiben', en: 'Sign delivery' },

  // Backup Request dialog
  'backup.dialogTitle': { de: 'Backup / Hilfe anfordern', en: 'Request backup / help' },
  'backup.request': { de: 'Hilfe anfordern', en: 'Request help' },
  'backup.kind': { de: 'Art der Hilfe', en: 'Type of help' },
  'backup.kind.driver': { de: 'Zusätzlicher Fahrer', en: 'Extra driver' },
  'backup.kind.vehicle': { de: 'Fahrzeug-Wechsel', en: 'Vehicle swap' },
  'backup.kind.fuel': { de: 'Kraftstoff/Pannenhilfe', en: 'Fuel / breakdown' },
  'backup.kind.tool': { de: 'Werkzeug/Ausrüstung', en: 'Tool / equipment' },
  'backup.kind.translator': { de: 'Dolmetscher', en: 'Translator' },
  'backup.kind.medical': { de: 'Medizinische Hilfe', en: 'Medical help' },
  'backup.urgency': { de: 'Dringlichkeit', en: 'Urgency' },
  'backup.urg.low': { de: 'Niedrig', en: 'Low' },
  'backup.urg.normal': { de: 'Normal', en: 'Normal' },
  'backup.urg.high': { de: 'Hoch', en: 'High' },
  'backup.urg.critical': { de: 'Kritisch', en: 'Critical' },
  'backup.title': { de: 'Kurze Überschrift', en: 'Short title' },
  'backup.titlePh': { de: 'z.B. Reifenpanne A2', en: 'e.g. Flat tire A2' },
  'backup.titleRequired': { de: 'Titel erforderlich', en: 'Title required' },
  'backup.delay': { de: 'Geschätzte Verspätung (Min.)', en: 'Estimated delay (min)' },
  'backup.criticalNote': { de: 'Bei Lebensgefahr zuerst 112 anrufen!', en: 'In life-threatening situations, call 112 first!' },
  'backup.send': { de: 'Senden', en: 'Send' },
  'backup.sent': { de: 'Backup-Anfrage gesendet', en: 'Backup request sent' },
  'backup.openCount': { de: 'Offene Anfragen', en: 'Open requests' },
  'backup.history': { de: 'Verlauf', en: 'History' },
  'backup.cancel': { de: 'Abbrechen', en: 'Cancel' },
  'backup.status.open': { de: 'Offen', en: 'Open' },
  'backup.status.acknowledged': { de: 'Bestätigt', en: 'Acknowledged' },
  'backup.status.dispatched': { de: 'Hilfe unterwegs', en: 'Help dispatched' },
  'backup.status.resolved': { de: 'Erledigt', en: 'Resolved' },
  'backup.status.cancelled': { de: 'Abgebrochen', en: 'Cancelled' },

  // Post-trip checklist
  'postTrip.title': { de: 'Schicht-Abschluss', en: 'End-of-shift' },
  'postTrip.locked': { de: 'Fahrzeug abgeschlossen', en: 'Vehicle locked' },
  'postTrip.fridge': { de: 'Kühlung ausgeschaltet', en: 'Fridge off' },
  'postTrip.cargo': { de: 'Laderaum gereinigt', en: 'Cargo area clean' },
  'postTrip.bins': { de: 'Behälter zurückgebracht', en: 'Bins returned' },
  'postTrip.paperwork': { de: 'Belege abgegeben', en: 'Paperwork submitted' },
  'postTrip.keys': { de: 'Schlüssel übergeben', en: 'Keys handed over' },
  'postTrip.adblue': { de: 'AdBlue aufgefüllt (falls nötig)', en: 'AdBlue refilled (if needed)' },
  'postTrip.endKm': { de: 'End-KM', en: 'End KM' },
  'postTrip.fuel': { de: 'Tank %', en: 'Fuel %' },
  'postTrip.damage': { de: 'Neue Schäden bemerkt', en: 'New damage noticed' },
  'postTrip.damagePh': { de: 'Beschreibung', en: 'Description' },
  'postTrip.cash': { de: 'Bargeld übergeben', en: 'Cash handed over' },
  'postTrip.signature': { de: 'Fahrer-Unterschrift', en: 'Driver signature' },
  'postTrip.complete': { de: 'Schicht abschließen', en: 'Complete shift' },
  'postTrip.update': { de: 'Aktualisieren', en: 'Update' },
  'postTrip.saved': { de: 'Schicht-Abschluss gespeichert', en: 'End-of-shift saved' },
  'postTrip.requiredMissing': { de: 'Pflichtpunkte nicht erfüllt', en: 'Required items missing' },
  'postTrip.alreadyDone': { de: 'Bereits eingereicht — Aktualisierung möglich', en: 'Already submitted — can update' },
  'postTrip.menuLabel': { de: 'Schicht-Abschluss', en: 'End of shift' },

  // Photo capture (odometer / fuel)
  'photo.take': { de: 'Foto aufnehmen', en: 'Take photo' },
  'photo.uploading': { de: 'Lädt hoch…', en: 'Uploading…' },
  'photo.captured': { de: '✓ Foto gespeichert', en: '✓ Photo saved' },
  'photo.odometer': { de: 'Kilometerstand-Foto', en: 'Odometer photo' },
  'photo.odometerHint': { de: 'Foto vom Tacho — Pflicht für Nachweis', en: 'Photo of dashboard — required as proof' },
  'photo.fuel': { de: 'Tankanzeige-Foto', en: 'Fuel gauge photo' },
  'photo.fuelHint': { de: 'Foto der Tankanzeige', en: 'Photo of fuel gauge' },
  'photo.required': { de: 'Foto erforderlich', en: 'Photo required' },

  // KM deviation
  'kmDev.title': { de: 'KM-Abweichung', en: 'KM deviation' },
  'kmDev.detected': { de: 'Privatnutzung erkannt: {km} km', en: 'Personal use detected: {km} km' },
  'kmDev.explain': { de: 'Bitte erklären (z.B. Heimweg)', en: 'Please explain (e.g. drive home)' },
  'kmDev.explainPh': { de: 'Grund eingeben…', en: 'Enter reason…' },
  'kmDev.send': { de: 'An Admin senden', en: 'Send to admin' },
  'kmDev.sent': { de: 'Erklärung gesendet', en: 'Explanation sent' },

  // NewCustomer
  'newCust.title': { de: 'Neukunde', en: 'New Customer' },
  'newCust.info': { de: 'Info', en: 'Info' },
  'newCust.contract': { de: 'Vertrag', en: 'Contract' },
  'newCust.containers': { de: 'Behälter', en: 'Containers' },
  'newCust.signature': { de: 'Unterschrift', en: 'Signature' },
  'newCust.receipt': { de: 'Beleg', en: 'Receipt' },
  'newCust.businessName': { de: 'Betriebsname *', en: 'Business name *' },
  'newCust.contact': { de: 'Ansprechpartner *', en: 'Contact person *' },
  'newCust.address': { de: 'Adresse *', en: 'Address *' },
  'newCust.phone': { de: 'Telefon *', en: 'Phone *' },
  'newCust.email': { de: 'E-Mail', en: 'Email' },
  'newCust.notes': { de: 'Notizen', en: 'Notes' },
  'newCust.notesPlaceholder': { de: 'Besondere Hinweise...', en: 'Special notes...' },
  'newCust.contractTitle': { de: 'Sammelvertrag', en: 'Collection Contract' },
  'newCust.contractSub': { de: 'Altöl & Speisefett Entsorgung', en: 'Used oil & cooking fat disposal' },
  'newCust.showContract': { de: 'Bitte zeigen Sie diesen Vertrag dem Kunden vor der Unterschrift.', en: 'Please show this contract to the customer before signing.' },
  'newCust.containersTitle': { de: 'Behälter für Neukunde', en: 'Containers for new customer' },
  'newCust.scanHint': { de: 'Scannen Sie die Behälter, die Sie dem neuen Kunden übergeben.', en: 'Scan the containers you are handing to the new customer.' },
  'newCust.custSignature': { de: 'Kundenunterschrift', en: 'Customer signature' },
  'newCust.signatureSaved': { de: 'Unterschrift gespeichert', en: 'Signature saved' },
  'newCust.resignBtn': { de: 'Erneut unterschreiben', en: 'Sign again' },
  'newCust.registered': { de: 'Neukunde registriert!', en: 'New customer registered!' },
  'newCust.customerNo': { de: 'Kundennummer', en: 'Customer number' },
  'newCust.business': { de: 'Betrieb', en: 'Business' },
  'newCust.contactLabel': { de: 'Kontakt', en: 'Contact' },
  'newCust.containersLabel': { de: 'Behälter', en: 'Containers' },
  'newCust.pieces': { de: 'Stück', en: 'pieces' },
  'newCust.printReceipt': { de: 'Beleg drucken', en: 'Print receipt' },
  'newCust.saveFinish': { de: 'Speichern & Fertig ✓', en: 'Save & Done ✓' },
  'newCust.back': { de: 'Zurück', en: 'Back' },
  'newCust.next': { de: 'Weiter', en: 'Next' },

  // NewCustomer - Opening Hours step
  'newCust.hours': { de: 'Öffnungszeiten', en: 'Opening Hours' },
  'newCust.hours.title': { de: 'Öffnungszeiten & Zugang', en: 'Opening hours & access' },
  'newCust.hours.subtitle': { de: 'Wann ist der Betrieb für Abholungen erreichbar?', en: 'When is the business available for pickups?' },
  'newCust.hours.weekly': { de: 'Wöchentliche Öffnungszeiten', en: 'Weekly opening hours' },
  'newCust.hours.mon': { de: 'Montag', en: 'Monday' },
  'newCust.hours.tue': { de: 'Dienstag', en: 'Tuesday' },
  'newCust.hours.wed': { de: 'Mittwoch', en: 'Wednesday' },
  'newCust.hours.thu': { de: 'Donnerstag', en: 'Thursday' },
  'newCust.hours.fri': { de: 'Freitag', en: 'Friday' },
  'newCust.hours.sat': { de: 'Samstag', en: 'Saturday' },
  'newCust.hours.sun': { de: 'Sonntag', en: 'Sunday' },
  'newCust.hours.closed': { de: 'Geschlossen', en: 'Closed' },
  'newCust.hours.copyMon': { de: 'Alle wie Montag übernehmen', en: 'Copy Monday to all days' },
  'newCust.hours.preferred': { de: 'Beste Abholzeit', en: 'Preferred pickup window' },
  'newCust.hours.preferredHint': { de: 'Innerhalb dieses Zeitfensters möchte der Kunde am liebsten beliefert werden.', en: 'Customer prefers pickup within this time window.' },
  'newCust.hours.from': { de: 'von', en: 'from' },
  'newCust.hours.to': { de: 'bis', en: 'to' },
  'newCust.hours.holidays': { de: 'An deutschen Feiertagen geschlossen', en: 'Closed on German public holidays' },
  'newCust.hours.specialClosures': { de: 'Sonderzeiten / Schließtage', en: 'Special closures' },
  'newCust.hours.specialClosuresPh': { de: 'z.B. Betriebsurlaub 24.12.–02.01., Ramadan-Zeiten...', en: 'e.g. Company holidays Dec 24 – Jan 2, Ramadan hours...' },
  'newCust.hours.access': { de: 'Zugangshinweise', en: 'Access notes' },
  'newCust.hours.accessPh': { de: 'z.B. Eingang hinten, vor Öffnung anrufen...', en: 'e.g. Rear entrance, call before arrival...' },

  // Incident Reporter
  'incident.title': { de: 'Problem melden', en: 'Report Problem' },
  'incident.traffic': { de: 'Stau / Verkehr', en: 'Traffic Jam' },
  'incident.trafficDesc': { de: 'Im Stau stecken geblieben', en: 'Stuck in traffic' },
  'incident.flatTire': { de: 'Reifenpanne', en: 'Flat Tire' },
  'incident.flatTireDesc': { de: 'Reifen ist platt', en: 'Tire is flat' },
  'incident.breakdown': { de: 'Fahrzeugpanne', en: 'Breakdown' },
  'incident.breakdownDesc': { de: 'Fahrzeug funktioniert nicht', en: 'Vehicle not working' },
  'incident.fuel': { de: 'Tanken notwendig', en: 'Need to refuel' },
  'incident.fuelDesc': { de: 'Muss tanken fahren', en: 'Need to go refuel' },
  'incident.accident': { de: 'Unfall', en: 'Accident' },
  'incident.accidentDesc': { de: 'In einen Unfall verwickelt', en: 'Involved in an accident' },
  'incident.other': { de: 'Sonstiges', en: 'Other' },
  'incident.otherDesc': { de: 'Anderes Problem', en: 'Other problem' },
  'incident.delay': { de: 'Geschätzte Verspätung (Minuten)', en: 'Estimated delay (minutes)' },
  'incident.note': { de: 'Notiz (optional)', en: 'Note (optional)' },
  'incident.notePlaceholder': { de: 'Weitere Details...', en: 'More details...' },
  'incident.submit': { de: 'An Disposition melden', en: 'Report to dispatch' },
  'incident.reported': { de: 'Gemeldet!', en: 'Reported!' },
  'incident.reportedSub': { de: 'Disposition wurde benachrichtigt.', en: 'Dispatch has been notified.' },

  // OtherContainersPicker
  'otherPicker.placeholder': { de: 'Andere Behälterart eingeben…', en: 'Enter other container type…' },
  'otherPicker.add': { de: 'Hinzufügen', en: 'Add' },

  // SafetyNotification
  'safety.tirePressure': { de: 'Reifendruck prüfen', en: 'Check tire pressure' },
  'safety.tirePressureMsg': { de: 'Empfohlen: 3.5 bar (vorne), 4.0 bar (hinten)', en: 'Recommended: 3.5 bar (front), 4.0 bar (rear)' },
  'safety.speed': { de: 'Geschwindigkeit beachten', en: 'Watch your speed' },
  'safety.speedMsg': { de: 'Innerorts max. 50 km/h', en: 'Urban areas max. 50 km/h' },
  'safety.oilLevel': { de: 'Ölstand kontrollieren', en: 'Check oil level' },
  'safety.oilLevelMsg': { de: 'Nächste Wartung in 3 Tagen', en: 'Next maintenance in 3 days' },
  'safety.rain': { de: 'Regenwarnung ab 14:00', en: 'Rain warning from 2 PM' },
  'safety.rainMsg': { de: 'Abstand halten & Geschwindigkeit anpassen', en: 'Keep distance & adjust speed' },

  // LeaveRequests extras
  'leave.hourly': { de: 'Stundenweise', en: 'Hourly' },
  'leave.hourlyInfo': { de: 'Stundenweise Freistellung für Termine, Behördengänge etc.', en: 'Hourly leave for appointments, errands, etc.' },
  'leave.date': { de: 'Datum', en: 'Date' },
  'leave.fromTime': { de: 'Von (Uhrzeit)', en: 'From (time)' },
  'leave.toTime': { de: 'Bis (Uhrzeit)', en: 'To (time)' },
  'leave.duration': { de: 'Dauer', en: 'Duration' },
  'leave.hours': { de: 'Std.', en: 'hrs' },
  'leave.mins': { de: 'Min.', en: 'min' },
  'leave.reasonPlaceholderVacation': { de: 'z.B. Familienurlaub', en: 'e.g. Family vacation' },
  'leave.reasonPlaceholderSick': { de: 'z.B. Erkältung', en: 'e.g. Cold/flu' },
  'leave.sickLabel': { de: 'Krankmeldung', en: 'Sick Report' },
  'leave.statVacation': { de: 'Urlaub', en: 'Vacation' },
  'leave.statHours': { de: 'Stunden', en: 'Hours' },
  'leave.statOpen': { de: 'Offen', en: 'Open' },
  'leave.statSick': { de: 'Krank', en: 'Sick' },

  // Performance activity log
  'activity.workStarted': { de: 'Arbeit gestartet', en: 'Work started' },
  'activity.driveToCustomer': { de: 'Fahrt zu Kunde', en: 'Driving to customer' },
  'activity.slowDrive': { de: 'Langsame Fahrt', en: 'Slow driving' },
  'activity.normalDrive': { de: 'Normalfahrt', en: 'Normal driving' },
  'activity.stopCustomer': { de: 'Stopp – Kunde', en: 'Stop – Customer' },
  'activity.trafficSlow': { de: 'Stau / langsam', en: 'Traffic / slow' },
  'activity.idle': { de: 'Leerlauf / Warten', en: 'Idle / Waiting' },
  'activity.breakSystem': { de: 'Pause (System)', en: 'Break (System)' },

  // Fahrernachweis
  'fn.title': { de: 'Fahrernachweis', en: 'Driver Activity Log' },
  'fn.subtitle': { de: 'Arbeitszeitnachweis gemäß EU/DE-Recht · 28-Tage-Protokoll', en: 'Working time record per EU/DE law · 28-day log' },
  'fn.compliant': { de: 'Konform — keine Lücken', en: 'Compliant — no gaps' },
  'fn.todayView': { de: 'Heute', en: 'Today' },
  'fn.todayViewSub': { de: 'Aktuelle Tagesübersicht & Vist-Log', en: 'Current day overview & visit log' },
  'fn.last28': { de: 'Letzte 28 Tage', en: 'Last 28 Days' },
  'fn.last28Sub': { de: 'Vollständiges Protokoll für Kontrolle', en: 'Full log for inspection' },
  'fn.inspection': { de: 'Kontrollmodus', en: 'Inspection Mode' },
  'fn.inspectionSub': { de: 'Schnellanzeige für Polizei / Behörde', en: 'Quick display for police / authority' },
  'fn.quickStats': { de: 'Schnellüberblick', en: 'Quick Stats' },
  'fn.daysLogged': { de: 'Tage erfasst', en: 'Days logged' },
  'fn.gaps': { de: 'Lücken', en: 'Gaps' },
  'fn.compliantShort': { de: 'Konform', en: 'Compliant' },
  'fn.workTime': { de: 'Arbeitszeit', en: 'Work Time' },
  'fn.driveTime': { de: 'Fahrzeit', en: 'Drive Time' },
  'fn.breakTime': { de: 'Pause', en: 'Break' },
  'fn.visitCount': { de: 'Besuche', en: 'Visits' },
  'fn.stops': { de: 'Stopps', en: 'Stops' },
  'fn.visitsToday': { de: 'Heutige Besuche', en: "Today's Visits" },
  'fn.noVisits': { de: 'Keine Besuche heute', en: 'No visits today' },
  'fn.statusWorked': { de: 'Gearbeitet', en: 'Worked' },
  'fn.op.collection': { de: 'Sammlung', en: 'Collection' },
  'fn.op.delivery': { de: 'Lieferung', en: 'Delivery' },
  'fn.op.inspection': { de: 'Prüfung', en: 'Inspection' },
  'fn.last28Days': { de: 'Heute + 28 Tage', en: 'Today + 28 Days' },
  'fn.gapsFound': { de: 'Lücken gefunden', en: 'gaps found' },
  'fn.noGapsFound': { de: 'Keine Lücken', en: 'No gaps' },
  'fn.date': { de: 'Datum', en: 'Date' },
  'fn.status': { de: 'Status', en: 'Status' },
  'fn.work': { de: 'Arbeit', en: 'Work' },
  'fn.drive': { de: 'Fahrt', en: 'Drive' },
  'fn.status.worked': { de: 'Arbeit', en: 'Work' },
  'fn.status.sick': { de: 'Krank', en: 'Sick' },
  'fn.status.vacation': { de: 'Urlaub', en: 'Vacation' },
  'fn.status.rest_day': { de: 'Ruhe', en: 'Rest' },
  'fn.status.training': { de: 'Schulung', en: 'Training' },
  'fn.dayDetail': { de: 'Tagesdetail', en: 'Day Detail' },
  'fn.visitList': { de: 'Besuchsliste', en: 'Visit List' },
  'fn.noWorkData': { de: 'Kein Arbeitstag — keine Daten verfügbar', en: 'Not a work day — no data available' },
  'fn.menuLabel': { de: 'Fahrernachweis', en: 'Driver Log' },
  'fn.menuSub': { de: '28-Tage-Protokoll & Kontrolle', en: '28-day log & inspection' },

  // Offline / Sync
  'offline.offline': { de: 'Offline – Daten werden gespeichert', en: 'Offline – data is saved' },
  'offline.pending': { de: 'ausstehend', en: 'pending' },
  'offline.syncing': { de: 'Synchronisiere…', en: 'Syncing…' },
  'offline.synced': { de: 'Synchronisiert', en: 'Synced' },

  // Pre-trip inspection
  'inspect.title': { de: 'Fahrzeug-Check vor Fahrtantritt', en: 'Pre-trip vehicle inspection' },
  'inspect.subtitle': { de: 'Pflicht laut DGUV V70 – täglich vor der ersten Fahrt', en: 'Required by DGUV V70 – daily before first trip' },
  'inspect.brakes': { de: 'Bremsen funktionieren', en: 'Brakes working' },
  'inspect.tires': { de: 'Reifen i.O. (Profil, Druck)', en: 'Tires OK (tread, pressure)' },
  'inspect.lights': { de: 'Beleuchtung & Blinker', en: 'Lights & indicators' },
  'inspect.oil': { de: 'Ölstand', en: 'Oil level' },
  'inspect.adblue': { de: 'AdBlue / Kühlflüssigkeit', en: 'AdBlue / coolant' },
  'inspect.body': { de: 'Karosserie ohne neue Schäden', en: 'No new body damage' },
  'inspect.firstAid': { de: 'Verbandkasten vorhanden', en: 'First-aid kit present' },
  'inspect.fireExt': { de: 'Feuerlöscher gültig', en: 'Fire extinguisher valid' },
  'inspect.vest': { de: 'Warnweste', en: 'Reflective vest' },
  'inspect.triangle': { de: 'Warndreieck', en: 'Warning triangle' },
  'inspect.startKm': { de: 'Kilometerstand', en: 'Odometer (km)' },
  'inspect.fuel': { de: 'Tankfüllung (%)', en: 'Fuel level (%)' },
  'inspect.defects': { de: 'Mängel / Anmerkungen', en: 'Defects / notes' },
  'inspect.defectsPlaceholder': { de: 'Beschreibe Mängel falls vorhanden…', en: 'Describe defects if any…' },
  'inspect.signature': { de: 'Unterschrift Fahrer', en: 'Driver signature' },
  'inspect.confirm': { de: 'Check abschließen', en: 'Complete check' },
  'inspect.blocked': { de: 'Fahrt gesperrt – Mängel an Disponent melden', en: 'Driving blocked – report defects to dispatcher' },
  'inspect.allOk': { de: 'Alle Punkte bestätigen oder Mängel melden', en: 'Confirm all items or report defects' },
  'inspect.required': { de: 'Bitte alle sicherheitsrelevanten Punkte prüfen', en: 'Please check all safety-relevant items' },

  // Fatigue alert
  'fatigue.preWarn.title': { de: 'Bald Pause nötig', en: 'Break needed soon' },
  'fatigue.preWarn.body': { de: 'In {min} Min. ist eine 45-Min.-Pause Pflicht (EU 561/2006).', en: 'In {min} min a 45-min break is mandatory (EU 561/2006).' },
  'fatigue.hard.title': { de: '⚠️ Pflichtpause jetzt!', en: '⚠️ Mandatory break now!' },
  'fatigue.hard.body': { de: 'Du fährst seit 4,5 Std. – jetzt 45 Min. Pause machen.', en: 'You\'ve been driving 4.5 h – take a 45-min break now.' },
  'fatigue.takeBreak': { de: 'Pause starten', en: 'Start break' },

  // Vehicle service alerts
  'vehicle.alerts.title': { de: 'Fahrzeug-Hinweise', en: 'Vehicle alerts' },
  'vehicle.alert.tuv': { de: 'TÜV läuft ab', en: 'TÜV expiring' },
  'vehicle.alert.service': { de: 'Service fällig', en: 'Service due' },
  'vehicle.alert.oil_change': { de: 'Ölwechsel fällig', en: 'Oil change due' },
  'vehicle.alert.tires': { de: 'Reifenwechsel', en: 'Tire change' },
  'vehicle.alert.insurance': { de: 'Versicherung läuft ab', en: 'Insurance expiring' },
  'vehicle.dismiss': { de: 'Für 7 Tage ausblenden', en: 'Dismiss for 7 days' },

  // Incident reporter (enhanced)
  'incident.photo': { de: 'Foto hinzufügen', en: 'Add photo' },
  'incident.voiceNote': { de: 'Sprachnotiz', en: 'Voice note' },
  'incident.injuries': { de: 'Personenschaden', en: 'Injuries' },
  'incident.notDrivable': { de: 'Fahrzeug nicht fahrbereit', en: 'Vehicle not drivable' },
  'incident.policeNumber': { de: 'Polizei-Aktenzeichen', en: 'Police report number' },
  'incident.otherParty': { de: 'Beteiligte (Kennzeichen, Name)', en: 'Other party (plate, name)' },
  'incident.sendUrgent': { de: 'Sofort an Disponent senden', en: 'Send urgent to dispatcher' },
  // Fill prediction
  'fill.title': { de: 'KI-Füllstand-Prognose', en: 'AI Fill Prediction' },
  'fill.refresh': { de: 'Aktualisieren', en: 'Refresh' },
  'fill.fullBy': { de: 'Voll bis', en: 'Full by' },
  'fill.unknownDate': { de: 'Datum unbekannt', en: 'Date unknown' },
  'fill.confidence': { de: 'Vertrauen', en: 'Confidence' },
  'fill.noData': { de: 'Noch keine Prognose – auf "Aktualisieren" tippen.', en: 'No prediction yet — tap "Refresh".' },

  // Upsell
  'upsell.title': { de: 'Container-Upsell', en: 'Bin Upsell' },
  'upsell.suggest': { de: 'Vorschlagen', en: 'Suggest' },
  'upsell.accepted': { de: 'Akzeptiert', en: 'Accepted' },
  'upsell.declined': { de: 'Abgelehnt', en: 'Declined' },
  'upsell.notePh': { de: 'Notiz für Backoffice (optional)…', en: 'Note for back-office (optional)…' },
  'upsell.saved': { de: 'Vorschlag gespeichert', en: 'Suggestion saved' },
  'upsell.failed': { de: 'Speichern fehlgeschlagen', en: 'Failed to save' },
  'upsell.thanks': { de: 'Danke – an Backoffice gesendet.', en: 'Thanks — sent to back-office.' },
  'upsell.type.extra_bin': { de: 'Extra-Behälter', en: 'Extra Bin' },
  'upsell.type.larger_container': { de: 'Größerer Behälter', en: 'Larger Container' },
  'upsell.type.extra_pickup': { de: 'Zusätzliche Abholung', en: 'Extra Pickup' },
} as const;

type TranslationKey = keyof typeof translations;

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>(() => {
    const saved = localStorage.getItem('app-lang');
    return (saved === 'en' || saved === 'de') ? saved : 'de';
  });

  const changeLang = useCallback((newLang: Lang) => {
    setLang(newLang);
    localStorage.setItem('app-lang', newLang);
  }, []);

  const t = useCallback((key: TranslationKey): string => {
    return translations[key]?.[lang] ?? key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
