// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSecure, removeSecure, setSecure } from '@/lib/security/secureStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: {
      getItem: (key: string) => getSecure(key),
      setItem: (key: string, value: string) => setSecure(key, value),
      removeItem: (key: string) => removeSecure(key),
    },
    persistSession: true,
    autoRefreshToken: true,
  }
});
